version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: event-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: eventdb

volumes:
  mongo-data:
